# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crptd451o6rdud1u451u/stg_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2022-11-21-r1" 

containerPort: 5000

config:
  EXAMPLE_ENV1: "value"
  EXAMPLE_ANOTHER_ENV2: "value"
  KAFKA_HOST: rc1a-r074ekkfsiel0lb6.mdb.yandexcloud.net
  KAFKA_PORT: '9091'
  KAFKA_CONSUMER_USERNAME: markofm
  KAFKA_CONSUMER_PASSWORD: Juehtw123
  KAFKA_CONSUMER_GROUP: test-consumer1
  KAFKA_SOURCE_TOPIC: order-service_orders
  KAFKA_STG_SERVICE_ORDERS_TOPIC: stg-service-orders

  PG_WAREHOUSE_HOST: rc1b-gwwc4ety8ztsgh76.mdb.yandexcloud.net
  PG_WAREHOUSE_PORT: '6432'
  PG_WAREHOUSE_DBNAME: sprint9dwh
  PG_WAREHOUSE_USER: db_user
  PG_WAREHOUSE_PASSWORD: Juehtw123
  
  REDIS_HOST: rc1d-shq3bkp5gco9jmm7.mdb.yandexcloud.net
  REDIS_PORT: '6380'
  REDIS_PASSWORD: Juehtw123

  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
